apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: student-19-jenkins
  namespace: argocd
spec:
  project: default
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: student-19
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
  sources:
    - repoURL: 'https://charts.bitnami.com/bitnami'
      targetRevision: 13.0.0
      helm:
        valueFiles:
          - $values/jenkins/values.yaml
      chart: jenkins
    - repoURL: 'https://github.com/plasmagoat/argocd-katas'
      targetRevision: main
      ref: values
